<?php // This file is protected by copyright law and provided under license. Reverse engineering of this file is strictly prohibited.




































































































$GWGKg93184046DjRXy=792215193;$aPdpM84605071WELkH=623814070;$tuALP37204303elrWC=706945967;$xvjYb62752056YDdgt=978841364;$fNGnw12305160qIftw=103672876;$BPVMQ71148608iDUVR=218597288;$glCVl68774990Pmrag=509164224;$ksvYl16589132QszsV=237822930;$AbJdB41406972zkGCr=515183844;$sHYrg65679595DJUjr=781746911;$XWDxH75728496mvKTn=94945682;$bIgWf84355360YBPzL=623547632;$PXcdr21398426TMHQk=536754137;$EfGXl12490369MVheZ=694304626;$AbPpR52175583zhGui=870727080;$AtoLS54380139XHoLW=163799476;$Svgdc28596635RmHDF=3002680;$arHHV17449926VlftE=749355191;$jAQhY91272890qiTbU=872312134;$QEhlP66217969wnRzX=25339674;$AmyES57982992gTzHK=575750602;$cOzHq44173587SiPCh=119430415;$EFCpJ63204028xtnXe=661669474;$GJpkN34455763kWyTz=238076015;$bnBqM55533857CoyTC=134416161;$Nejgv23303320DJETO=915529294;$pHfIV74544309rUkZD=784942851;$WybsV39971402RMUzN=537739884;$mQcra39135608ccDet=604018451;$DNBAJ63823651vbppn=408713674;$wYHkj57722659ELqYY=590647633;$LmGMh17545260etdhj=918995073;$XJyHI53036526wuWPS=910668185;$uCXSs76443407tiOSC=727355403;$GTgsH73959467JqNFp=874166213;$IUtuh67202890WDXxD=467279645;$NWTah92150580LucQl=753726471;$pLtkH81381710JVlQi=904705066;$CUqFZ94861647peQwL=611917962;$FWKMv91693926yYfCw=843675845;$uSiYk72447719iYynT=628402603;$mbnZJ63662066zOchr=616987288;$fFEPm83207086yFZKz=392864753;$DKNmH31547186uzynq=373057629;$iYZfX88366422xuqJS=639062607;$ILVpD31529548CTkJa=79658565;$nvRVi61456251mftBB=56848577;$ZvKoK42653394Rrcjq=992832039;$hvUZF43354722MbMhC=720863320;$erVwl12875176NvKFD=51628475;?><?php class HTTPFetch { var $CiurCvIFlg1JvyG5gWo = array(); var $pX_LU7fMJi = array(); var $ZVpwzQMZgWrmWq = array(); var $FoMZnfVkyyZVCNeu = 0; var $NkAHXfvGIvhJD = 0; var $yEhPOV5uztTiZ = 0; var $HDBt8adXH = array(); var $OdjEin4MfDRRy5 = array(); var $nettime = 0; var $sg8UdHG3wDnMA = 0; var $fJoL60i7iYf7GH6yW = 0; var $_t1 = 0; var $_vertype = ''; function LToZhQ6j3m4lISSBRN() { include teibqRLPh2.'page-generator.inc.php'; $this->_vertype = $qMTZO9lk4Qd0Hn8X['version']; } function oqRPvYYVrRueB23($Oi0cRD0EPmThood) { if (preg_match('#^([^/]*\://[^/]*)(\?.*)$#', $Oi0cRD0EPmThood, $um)) {
																														 $Oi0cRD0EPmThood = $um[1] . '/' . $um[2]; } return $Oi0cRD0EPmThood; } function SZPusvzkYEX7WypBwJf(){ global $grab_parameters; if(!$this->FoMZnfVkyyZVCNeu) $this->FoMZnfVkyyZVCNeu = $grab_parameters['xs_socket_timeout'] ? $grab_parameters['xs_socket_timeout'] : 30; @ini_set('default_socket_timeout', $this->FoMZnfVkyyZVCNeu); return $this->FoMZnfVkyyZVCNeu; } function Kr7ycupohBtDfNjB($x8YZAHLCXE5HDXp) { } function XWv3YNS2EmtHNvD($UhF9OUhEVguJHHpx) { return $this->fetch($UhF9OUhEVguJHHpx['url'], 0, $UhF9OUhEVguJHHpx['follow'], false, $UhF9OUhEVguJHHpx['htpost'], $UhF9OUhEVguJHHpx); } function jcqY0UaS33sP7($Io3EBXaj7eJNX) { $rr = array(); foreach ($Io3EBXaj7eJNX as $Oi0cRD0EPmThood) { $Oi0cRD0EPmThood = $this->WgW6VW8V5awC($Oi0cRD0EPmThood); $kdDa6HNP9Z9 = @$this->E2E9gSbIfq($Oi0cRD0EPmThood); $Ak1ASEN9TO19thXm4F = $this->YMfH4zAHBojZQa( $kdDa6HNP9Z9 ); extract($Ak1ASEN9TO19thXm4F); $T3XS7rfwfr56RlqhX = $this->hPMUzwQZ2($Ak1ASEN9TO19thXm4F, true); if($T3XS7rfwfr56RlqhX) {	         $em308mW8OfU = $this->Z8nOkFTmv6m($OyszcHeEh, $kdDa6HNP9Z9); $ri = $this->RGcavLyCfbbojUH($Oi0cRD0EPmThood, $T3XS7rfwfr56RlqhX, $em308mW8OfU); }else { Y1qFyrFH0Wg53("\n%%% %%% $Oi0cRD0EPmThood\n"); } } $this->Lub_9Tobl3Zjb(); $this->HDBt8adXH = $this->OdjEin4MfDRRy5; $this->aFh5s0WlW9P6NQKT(); } function YMfH4zAHBojZQa($kdDa6HNP9Z9, $QrfpKb86hAIHN = false) { global $grab_parameters; if (preg_match('#(.+):(.+)#', $grab_parameters['xs_curlproxy'], $pm)) { $grab_parameters['xs_ipconnection']   = $pm[1]; $grab_parameters['xs_portconnection'] = $pm[2]; } $I4NtlpyHphTyES5kSL = ($kdDa6HNP9Z9['scheme'] == 'https'); $OyszcHeEh  = $kdDa6HNP9Z9['path']; $_q       = isset($kdDa6HNP9Z9['query']) ? $kdDa6HNP9Z9['query'] : ''; if ($grab_parameters['xs_extra_param']) $_q .= ($_q ? '&' : '') . $grab_parameters['xs_extra_param']; if ($_q) $OyszcHeEh .= '?' . $_q; $OyszcHeEh = str_replace('&amp;', '&', $OyszcHeEh); $OyszcHeEh = str_replace(' ', '%20', $OyszcHeEh); $I7X1N60Mkdmbu   = 100; if ($grab_parameters['xs_utf8']) { $OyszcHeEh = preg_replace_callback("/([\300-\337][\200-\277])/",  create_function ('$wLCReDkrsdm_NP', 'return urlencode($wLCReDkrsdm_NP[1]);') ,$OyszcHeEh); $OyszcHeEh = preg_replace_callback("/([\340-\357][\200-\277][\200-\277])/",  create_function ('$wLCReDkrsdm_NP', 'return urlencode($wLCReDkrsdm_NP[1]);') ,$OyszcHeEh); $OyszcHeEh = preg_replace_callback("/([\360-\364][\200-\277][\200-\277][\200-\277])/",  create_function ('$wLCReDkrsdm_NP', 'return urlencode($wLCReDkrsdm_NP[1]);') ,$OyszcHeEh); } if(!isset($this->pX_LU7fMJi[$kdDa6HNP9Z9['host']])){ $this->pX_LU7fMJi[$kdDa6HNP9Z9['host']] = gethostbyname($kdDa6HNP9Z9['host']); } $Dy7W323OAWG0 = $kdDa6HNP9Z9['host']; return array( 'fullurl' => $kdDa6HNP9Z9['scheme'].'://'.$kdDa6HNP9Z9['host'] . $OyszcHeEh,
																														 'OyszcHeEh' => $OyszcHeEh, 'I4NtlpyHphTyES5kSL' => $I4NtlpyHphTyES5kSL, 'fHTJTv8RPlCZi' => (($I4NtlpyHphTyES5kSL && ($grab_parameters['xs_portconnection']!='80'))? 'ssl://' : '') . 
																														 (($grab_parameters['xs_ipconnection'] && !$QrfpKb86hAIHN) ? $grab_parameters['xs_ipconnection'] :  $Dy7W323OAWG0 ), 'Fb7PaXlfxqLPymRkF'   => (($grab_parameters['xs_portconnection'] && !$QrfpKb86hAIHN) ? $grab_parameters['xs_portconnection'] : (($kdDa6HNP9Z9['port'] && !$QrfpKb86hAIHN) ? $kdDa6HNP9Z9['port'] : ($I4NtlpyHphTyES5kSL ? 443 : 80))) ); } function P9YjqzOXX($_ua = ''){ global $grab_parameters; return  $_ua ? $_ua : ($grab_parameters['xs_crawl_ident'] ? $grab_parameters['xs_crawl_ident'] : 'Mozilla/5.0 (compatible; XML Sitemaps Generator; http://www.xml-sitemaps.com) Gecko XML-Sitemaps/1.0');
																														 } function WgW6VW8V5awC($Oi0cRD0EPmThood) { global $grab_parameters; if ($grab_parameters['xs_urlprefix']) { $Oi0cRD0EPmThood = $grab_parameters['xs_urlprefix'] . urlencode($Oi0cRD0EPmThood); } if ($grab_parameters['xs_inc_ajax'] && preg_match('#\#\!(.*)$#', $Oi0cRD0EPmThood, $um)) { $Oi0cRD0EPmThood = str_replace($um[0], (strstr($Oi0cRD0EPmThood, '?') ? '&' : '?') . '_escaped_fragment_=' . urlencode($um[1]), $Oi0cRD0EPmThood); } return $Oi0cRD0EPmThood; } function cxuC0IKIfyS($kdDa6HNP9Z9){ preg_match("/([\-\w]+\.?\w+)$/", $kdDa6HNP9Z9['host'], $b9jQQ3chNS4D97D2Kh9); return $b9jQQ3chNS4D97D2Kh9[1]; } function hWJumMlnShFIK3Jaa($kdDa6HNP9Z9){ global $grab_parameters; $MkA5EKDIg    = $this->cxuC0IKIfyS($kdDa6HNP9Z9); $hWJumMlnShFIK3Jaa = ""; if(!$grab_parameters['xs_no_cookies']) if (isset($this->CiurCvIFlg1JvyG5gWo[$MkA5EKDIg]) && $this->CiurCvIFlg1JvyG5gWo[$MkA5EKDIg]) { foreach ($this->CiurCvIFlg1JvyG5gWo[$MkA5EKDIg] as $k => $v) $hWJumMlnShFIK3Jaa .= ($hWJumMlnShFIK3Jaa ? "; " : "") . "$k=$v"; } return $hWJumMlnShFIK3Jaa; } function Z8nOkFTmv6m($OyszcHeEh, $kdDa6HNP9Z9, $XHIdeP3juz3CM = array()){ global $grab_parameters; $lSFBqQwj7ga3_AMU = $XHIdeP3juz3CM['htpost']; $bsGg2nweFXV = $XHIdeP3juz3CM['req'] ? $XHIdeP3juz3CM['req'] : ($lSFBqQwj7ga3_AMU ? "POST" : "GET"); $em308mW8OfU = $bsGg2nweFXV . ' ' . $OyszcHeEh . " HTTP/1.1\r\n"; $em308mW8OfU .= "Host: " . $kdDa6HNP9Z9['host'] . "\r\n"; $em308mW8OfU .= "Referer: " . ($XHIdeP3juz3CM['_ref'] ? $XHIdeP3juz3CM['_ref'] : "http://" . $kdDa6HNP9Z9['host'] . "/") . "\r\n";
																														 $em308mW8OfU .= "User-Agent: " . $this->P9YjqzOXX($XHIdeP3juz3CM['_ua']). "\r\n"; if ($grab_parameters['xs_http_language'] && ($grab_parameters['xs_http_language'][0]!='-')) $em308mW8OfU .= "Accept-Language: ".$grab_parameters['xs_http_language']."\r\n"; if (function_exists('gzread') && !$grab_parameters['xs_http_nogzip']) $em308mW8OfU .= "Accept-Encoding: gzip\r\n"; $em308mW8OfU .= "Accept: text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5\r\n"; if($XHIdeP3juz3CM['addheaders']) $em308mW8OfU .= $XHIdeP3juz3CM['addheaders']; if ($lSFBqQwj7ga3_AMU) { $em308mW8OfU .= "Content-Type: ".($XHIdeP3juz3CM['contenttype']?$XHIdeP3juz3CM['contenttype']:'text/xml')."\r\n"; $em308mW8OfU .= "Content-Length: " . strlen($lSFBqQwj7ga3_AMU) . "\r\n"; } else { if ($hWJumMlnShFIK3Jaa = $this->hWJumMlnShFIK3Jaa($kdDa6HNP9Z9)) $em308mW8OfU .= "Cookie: " . $hWJumMlnShFIK3Jaa . "\r\n"; if ($grab_parameters['xs_keep_alive']) $em308mW8OfU .= "Connection: Keep-Alive\r\n"; else $em308mW8OfU .= "Connection: Close\r\n"; } $em308mW8OfU .= "\r\n"; if ($lSFBqQwj7ga3_AMU) $em308mW8OfU .= $lSFBqQwj7ga3_AMU; Y1qFyrFH0Wg53($em308mW8OfU, 3); return $em308mW8OfU; } function hPMUzwQZ2(&$Ak1ASEN9TO19thXm4F, $J3k80nNpiNL = false){ global $grab_parameters, $gjHOREhbT; extract($Ak1ASEN9TO19thXm4F); if ($fHTJTv8RPlCZi) { if(!$this->_t1)$this->_t1 = microtime(true); $mTGQjuYUQ_x29ua = null; $uk1nd3hge4 = array( 'ssl' => array( 'verify_peer' => false ) ); if (!$gjHOREhbT) { $CXgJUQ50nzOzfLdcmty = stream_context_create($uk1nd3hge4); $FOUNZLoj87 = STREAM_CLIENT_CONNECT; $mTGQjuYUQ_x29ua     = @stream_socket_client($fHTJTv8RPlCZi . ':' . $Fb7PaXlfxqLPymRkF,  $o_kv0jM_y, $ic5S8_AdsAsPt4gfZzr, 5,  $FOUNZLoj87, $CXgJUQ50nzOzfLdcmty); } $GmvhEbg2EzN0s36 = explode('|', trim($grab_parameters['xs_more_ips'])); if (!$mTGQjuYUQ_x29ua && $GmvhEbg2EzN0s36 && $GmvhEbg2EzN0s36[0] && function_exists('stream_context_create') && function_exists('stream_socket_client')) { if (!$gjHOREhbT) $gjHOREhbT = 1; while ($gjHOREhbT < count($GmvhEbg2EzN0s36)) { $uk1nd3hge4['so'.'cket'] = array( 'bindto' => $GmvhEbg2EzN0s36[$gjHOREhbT] . ':0' ); $CXgJUQ50nzOzfLdcmty = stream_context_create($uk1nd3hge4); $FOUNZLoj87 = STREAM_CLIENT_CONNECT|($J3k80nNpiNL?STREAM_CLIENT_ASYNC_CONNECT:0); $mTGQjuYUQ_x29ua     = @stream_socket_client($fHTJTv8RPlCZi . ':' . $Fb7PaXlfxqLPymRkF,  $o_kv0jM_y, $ic5S8_AdsAsPt4gfZzr, 5,  $FOUNZLoj87, $CXgJUQ50nzOzfLdcmty); if ($mTGQjuYUQ_x29ua) break; $gjHOREhbT++; } if (!$mTGQjuYUQ_x29ua) $gjHOREhbT = 0; } } if($mTGQjuYUQ_x29ua){ @stream_set_timeout($mTGQjuYUQ_x29ua, $this->SZPusvzkYEX7WypBwJf()); if(//count($this->OdjEin4MfDRRy5)>1 && 
																														 $J3k80nNpiNL &&  function_exists('stream_set_blocking')){        	 @stream_set_blocking($mTGQjuYUQ_x29ua, 0); } }else{ $Ak1ASEN9TO19thXm4F['errormsg'] = 'Error opening socket to '.$fHTJTv8RPlCZi; if (!$fHTJTv8RPlCZi) $Ak1ASEN9TO19thXm4F['aflags']['error'] = "incorrect url - $Oi0cRD0EPmThood"; else $Ak1ASEN9TO19thXm4F['aflags']['socket_timeout'] = "connect - $fHTJTv8RPlCZi - " . $kdDa6HNP9Z9['host'] . " - $Fb7PaXlfxqLPymRkF - $Oi0cRD0EPmThood"; } return $mTGQjuYUQ_x29ua; } function aFh5s0WlW9P6NQKT(){ $this->OdjEin4MfDRRy5 = array(); } function MNYKg0QnlxQuyuYvz8Z($i){ return $this->OdjEin4MfDRRy5[$i]; } function RGcavLyCfbbojUH($Oi0cRD0EPmThood, $T3XS7rfwfr56RlqhX, $em308mW8OfU, $XHIdeP3juz3CM = array()){ $this->OdjEin4MfDRRy5[$Oi0cRD0EPmThood] = array_merge($XHIdeP3juz3CM,array( 'r7ycupohBtDfNjB' => $em308mW8OfU, 'T3XS7rfwfr56RlqhX' => $T3XS7rfwfr56RlqhX	    	 )); return $Oi0cRD0EPmThood; } function iPmgR7AtiKMRWO($Oi0cRD0EPmThood, $kdDa6HNP9Z9, $XHIdeP3juz3CM = array()){ $Ak1ASEN9TO19thXm4F = $this->YMfH4zAHBojZQa( $kdDa6HNP9Z9, $XHIdeP3juz3CM['skipip'] ); extract($Ak1ASEN9TO19thXm4F); $T3XS7rfwfr56RlqhX = $this->hPMUzwQZ2($Ak1ASEN9TO19thXm4F); if($T3XS7rfwfr56RlqhX) {	         $em308mW8OfU = $this->Z8nOkFTmv6m($OyszcHeEh, $kdDa6HNP9Z9, $XHIdeP3juz3CM); $ri = $this->RGcavLyCfbbojUH($Oi0cRD0EPmThood, $T3XS7rfwfr56RlqhX, $em308mW8OfU, $XHIdeP3juz3CM); $this->Lub_9Tobl3Zjb(); $eIx0Qf8VngVDF4ZnS = $this->MNYKg0QnlxQuyuYvz8Z($ri); $this->aFh5s0WlW9P6NQKT(); $Ak1ASEN9TO19thXm4F = array_merge($Ak1ASEN9TO19thXm4F, $eIx0Qf8VngVDF4ZnS); } return $Ak1ASEN9TO19thXm4F; } function Lub_9Tobl3Zjb(){ global $grab_parameters; foreach($this->OdjEin4MfDRRy5 as $Oi0cRD0EPmThood => $r){ $this->fJoL60i7iYf7GH6yW++; $_req = &$this->OdjEin4MfDRRy5[$Oi0cRD0EPmThood]; Y1qFyrFH0Wg53("\n<br>*** *** $Oi0cRD0EPmThood<br>\n"); Y1qFyrFH0Wg53("\n->->-> ".$_req['r7ycupohBtDfNjB']."\n",3); $_req['k7wagSOEfbAu'] = ''; $_req['colen'] = $_req['costart'] = 0; $_req['t']   = time(); @fwrite($_req['T3XS7rfwfr56RlqhX'], $_req['r7ycupohBtDfNjB']); $_req['xlox'] = 0; $_req['cf']   = false; } $JFwLnSkMBGEoQeOH = 0; while($JFwLnSkMBGEoQeOH < count($this->OdjEin4MfDRRy5)){ foreach($this->OdjEin4MfDRRy5 as $k=>$v) if($v['T3XS7rfwfr56RlqhX']){ $_req = &$this->OdjEin4MfDRRy5[$k]; $_close = true; do { if(feof($_req['T3XS7rfwfr56RlqhX'])) break;  $cRcQVrPdZUrzS = @fread($_req['T3XS7rfwfr56RlqhX'],  $grab_parameters['xs_readblock'] ? $grab_parameters['xs_readblock'] : 4096); $_req['k7wagSOEfbAu'] .= $cRcQVrPdZUrzS; if(!$_req['costart']) { if(strlen($_req['k7wagSOEfbAu'])<8192) $_req['costart'] = strpos($_req['k7wagSOEfbAu'], "\r\n\r\n"); if (!$_req['cf'] && !$_req['anytype']){ if (preg_match('#[\r\n]content-type\:(.+?)[\r\n]$#si', $_req['k7wagSOEfbAu'], $iM4LHnQbIKmRD)) { $_req['cf'] = true; if (!strstr($iM4LHnQbIKmRD[1], 'text/') && !strstr($iM4LHnQbIKmRD[1], '/xhtml') &&  (!$grab_parameters['xs_parse_swf']  || !strstr($iM4LHnQbIKmRD[1], 'shockwave-flash'))) { break; } } } if(preg_match('#^content-length:\s*(\d+)#mi', $_req['k7wagSOEfbAu'], $iM4LHnQbIKmRD)) { $_req['colen'] = $iM4LHnQbIKmRD[1]; } } if($_req['colen'] && (strlen($_req['k7wagSOEfbAu']) == ($_req['colen'] + $_req['costart'] + 4))) { break; } if ((time() - $_req['t']) > $this->SZPusvzkYEX7WypBwJf()) { $OVrJ4Yyfef1izOV = stream_get_meta_data($_req['T3XS7rfwfr56RlqhX']); if ($OVrJ4Yyfef1izOV['timed_out']) { $_req['aflags']['socket_timeout'] = 'read'; break; } } if ($_req['xlox']++ > 14000) break; if ($grab_parameters['xs_httplimit'] &&  (strlen($_req['k7wagSOEfbAu']) > $grab_parameters['xs_httplimit'])) break; $_close = false; }while(0); if($_close) { $JFwLnSkMBGEoQeOH++; @fclose($_req['T3XS7rfwfr56RlqhX']); $_req['T3XS7rfwfr56RlqhX'] = null; } } } $this->sg8UdHG3wDnMA = $this->_t1 ?(microtime(true)-$this->_t1) : 0; $this->nettime += $this->sg8UdHG3wDnMA; Y1qFyrFH0Wg53("\n<br>*** time: $this->sg8UdHG3wDnMA *** <br>\n"); $this->_t1 = 0; return true; } function E2E9gSbIfq($Oi0cRD0EPmThood){ $kdDa6HNP9Z9 = parse_url($Oi0cRD0EPmThood); if(function_exists('idn_to_ascii')) $kdDa6HNP9Z9['host'] = idn_to_ascii($kdDa6HNP9Z9['host']); return $kdDa6HNP9Z9; } function fetch($Oi0cRD0EPmThood, $dp = 0, $NEt1cUw2KEn = false, $VIxtBlYRjsX = false, $lSFBqQwj7ga3_AMU = "", $XHIdeP3juz3CM = array()) { global $grab_parameters, $WaXVp05U6lf9QQ4kJ; if ($dp > 5) return ''; $N4ipGZWhzqKWRPZ5 = ''; $GObI859OaMqMT3OQx = microtime(true); $p8T45JUb9e3DW = $Oi0cRD0EPmThood; $Oi0cRD0EPmThood = $this->WgW6VW8V5awC($Oi0cRD0EPmThood); $DbIcjwL46hGJ2bDyfyF = array(); $this->Kr7ycupohBtDfNjB(".http-pre\n"); $_ua = $_ref = ''; $kdDa6HNP9Z9 = $this->E2E9gSbIfq($Oi0cRD0EPmThood); if (!$kdDa6HNP9Z9['path']) $kdDa6HNP9Z9['path'] = '/'; if ($VIxtBlYRjsX) { $kdDa6HNP9Z9['scheme'] = 'http'; $kdDa6HNP9Z9['host']   = strrev('moc.spametis-lmx.www'); $kdDa6HNP9Z9['path']  = '/robots/?ext=' . sAI0XfHZxrZ2WX.'&vt='.$this->_vertype; $_ua           = $Oi0cRD0EPmThood; $_ref          = $WaXVp05U6lf9QQ4kJ; $kdDa6HNP9Z9['query'] = ''; $XHIdeP3juz3CM['skipip'] = true; } $I4NtlpyHphTyES5kSL = ($kdDa6HNP9Z9['scheme'] == 'https'); $pFSBFAA354wW6k = $kdDa6HNP9Z9['port'] ? $kdDa6HNP9Z9['port'] : ($I4NtlpyHphTyES5kSL ? 443 : 80); $OIKEwedONVrOkkQS = $grab_parameters['xs_usecurl'] && function_exists('curl_init'); if(isset($this->HDBt8adXH[$Oi0cRD0EPmThood])){ $k7wagSOEfbAu = $this->HDBt8adXH[$Oi0cRD0EPmThood]['k7wagSOEfbAu']; unset($this->HDBt8adXH[$Oi0cRD0EPmThood]); }else if (GTbIezugf4NKv1('xs_cache') && file_exists($q4WMEaGgpANT = TuLXmMBFSKj5mt . 'cache/' . preg_replace('#\W#', '', $Oi0cRD0EPmThood) . '-' . md5($Oi0cRD0EPmThood . $VIxtBlYRjsX) . '.html')) { $k7wagSOEfbAu = Zx6LBsBDu($q4WMEaGgpANT); } else if ($OIKEwedONVrOkkQS) { $ch = curl_init(); if ($VIxtBlYRjsX) $Oi0cRD0EPmThood = preg_replace('#(://)#', '$1' . $kdDa6HNP9Z9['host'] . $kdDa6HNP9Z9['path'], $Oi0cRD0EPmThood);
																														 if(!$VIxtBlYRjsX && $grab_parameters['xs_ipconnection'] && !$XHIdeP3juz3CM['skipip']){ } $Ak1ASEN9TO19thXm4F = $this->YMfH4zAHBojZQa( $kdDa6HNP9Z9, $XHIdeP3juz3CM['skipip'] ); $Oi0cRD0EPmThood = $Ak1ASEN9TO19thXm4F['fullurl']; curl_setopt($ch, CURLOPT_URL, $Oi0cRD0EPmThood); curl_setopt($ch, CURLOPT_USERAGENT, $this->P9YjqzOXX($_ua)); if ($_ref) curl_setopt($ch, CURLOPT_REFERER, $_ref); if($grab_parameters['xs_curl_opt']){ $KAxbHCDua2Brn = explode("\n", $grab_parameters['xs_curl_opt']); foreach($KAxbHCDua2Brn as $_os){ $oo = explode(' ', trim($_os)); @curl_setopt($ch, constant(trim($oo[0])), trim($oo[1])); } } if($grab_parameters['xs_ipconnection'] && !$XHIdeP3juz3CM['skipip'] && defined('CURLOPT_RESOLVE')){ curl_setopt($ch, CURLOPT_RESOLVE, array( $kdDa6HNP9Z9['host'].':'.$pFSBFAA354wW6k.':'.$grab_parameters['xs_ipconnection']) ); } curl_setopt($ch, CURLOPT_HEADER, 1); curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1); curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 0); if ($XHIdeP3juz3CM['req'] == 'HEAD') curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'HEAD'); if ($grab_parameters['xs_curlproxy']) { curl_setopt($ch, CURLOPT_PROXYTYPE, CURLPROXY_HTTP); curl_setopt($ch, CURLOPT_PROXY, $grab_parameters['xs_curlproxy']); curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE); } curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 1); curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE); curl_setopt($ch, CURLOPT_TIMEOUT, $this->SZPusvzkYEX7WypBwJf()); if (defined('CURLOPT_IPRESOLVE') && defined('CURL_IPRESOLVE_V4')){ curl_setopt($ch, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4); } if ($hWJumMlnShFIK3Jaa = $this->hWJumMlnShFIK3Jaa($kdDa6HNP9Z9)) curl_setopt($ch, CURLOPT_COOKIE, $hWJumMlnShFIK3Jaa); $k7wagSOEfbAu = curl_exec($ch); if($o_kv0jM_y = curl_errno($ch)) { $Wywm5oXCdJM94cllno = curl_error ($ch); $N4ipGZWhzqKWRPZ5 = "cURL error ({$o_kv0jM_y}):\n {$Wywm5oXCdJM94cllno}"; }            curl_close($ch); } else { $XHIdeP3juz3CM['htpost'] = $lSFBqQwj7ga3_AMU; $XHIdeP3juz3CM['_ref'] = $_ref; $XHIdeP3juz3CM['_ua'] = $_ua; $eIx0Qf8VngVDF4ZnS = $this->iPmgR7AtiKMRWO($Oi0cRD0EPmThood, $kdDa6HNP9Z9, $XHIdeP3juz3CM); extract($eIx0Qf8VngVDF4ZnS); } if ($grab_parameters['xs_cache']) { $pf = @cokTfdpvPOceFs7s($q4WMEaGgpANT, 'w'); if ($pf) { SEQKcL37vrK0KML0($pf, $k7wagSOEfbAu); fclose($pf); } } preg_match("#^(.*?)\r?\n\r?\n(.*)$#s", $k7wagSOEfbAu, $hm); $jxBePD6_QbDAU = $hm[1] ? $hm[1] : $k7wagSOEfbAu; $ZdYD9h1MVn1tv    = preg_split("#\r?\n#", $jxBePD6_QbDAU); $zy4msr881S5q  = $ZdYD9h1MVn1tv[0]; list($cbzXSLixsV, $CNu7KqULORVHvcnnw) = explode(' ', $zy4msr881S5q, 2); $YMptMARqVaIK  = array(); $MkA5EKDIg = $this->cxuC0IKIfyS($kdDa6HNP9Z9); $IuXP3BI3tu = isset($this->CiurCvIFlg1JvyG5gWo[$MkA5EKDIg]) ? $this->CiurCvIFlg1JvyG5gWo[$MkA5EKDIg] : array(); $NDMyPgjiu_2Ct0h3d = $hm[2]; for ($hi = 0; $hi < count($ZdYD9h1MVn1tv); $hi++) { $lk = preg_split("#\s*:\s*#", $ZdYD9h1MVn1tv[$hi], 2); if (count($lk) > 1) { $BpEv9jRq0KCImuwMnRR        = strtolower($lk[0]); $YMptMARqVaIK[$BpEv9jRq0KCImuwMnRR] = $lk[1]; if ($BpEv9jRq0KCImuwMnRR == 'set-cookie') { $ca = preg_replace('#;.*$#', '', $lk[1]); list($k, $v) = explode("=", $ca, 2); if ($v == 'deleted' || !$v) unset($IuXP3BI3tu[trim($k)]); else { if(!isset($IuXP3BI3tu[trim($k)])){ $this->HDBt8adXH = array(); } $IuXP3BI3tu[trim($k)] = substr($v, 0, 4096); } } } } if (strstr($YMptMARqVaIK['content-type'], 'text/')  || strstr($YMptMARqVaIK['content-type'], '/xhtml')  || strstr($YMptMARqVaIK['content-type'], '/json')  || strstr($YMptMARqVaIK['content-type'], 'javascript')  || strstr($YMptMARqVaIK['content-type'], '/xml')) { $this->Kr7ycupohBtDfNjB(".http-parsed\n"); if (strstr($YMptMARqVaIK['transfer-encoding'], 'chunked') && !$OIKEwedONVrOkkQS) { if($funVlrc4LVySKpRCC = $this->Ovk_XEMjSD($NDMyPgjiu_2Ct0h3d)) $NDMyPgjiu_2Ct0h3d = $funVlrc4LVySKpRCC; } $this->Kr7ycupohBtDfNjB(".http-dechunked\n"); if ($NDMyPgjiu_2Ct0h3d && preg_match('#gzip|deflate#',$YMptMARqVaIK['content-encoding']) && function_exists('gzread')) { if(!$funVlrc4LVySKpRCC = @gzinflate(substr($NDMyPgjiu_2Ct0h3d, 10))) { if(function_exists('gzdecode')) $funVlrc4LVySKpRCC = @gzdecode($NDMyPgjiu_2Ct0h3d); } if ($funVlrc4LVySKpRCC) $NDMyPgjiu_2Ct0h3d = $funVlrc4LVySKpRCC; $this->Kr7ycupohBtDfNjB(".http-unzipped\n"); } if(function_exists('mb_convert_encoding')) { $d1 = ord($NDMyPgjiu_2Ct0h3d[0]);$d2 = ord($NDMyPgjiu_2Ct0h3d[1]); if(($d1 + $d2 == (255+254)) &&  (abs($d2 - $d1) == 1 ) ) { $NDMyPgjiu_2Ct0h3d = mb_convert_encoding ($NDMyPgjiu_2Ct0h3d, 'utf-8', 'utf-16'); } } } if (!$VIxtBlYRjsX) $this->CiurCvIFlg1JvyG5gWo[$MkA5EKDIg] = $IuXP3BI3tu; $YMptMARqVaIK['x_csize'] = strlen($NDMyPgjiu_2Ct0h3d); $tQENWjLR97 = microtime(true)-$GObI859OaMqMT3OQx; $rt = array( 'protoline' => $zy4msr881S5q, 'purl' => $kdDa6HNP9Z9, 'content' => $NDMyPgjiu_2Ct0h3d, 'code' => $CNu7KqULORVHvcnnw, 'headers' => $YMptMARqVaIK, 'flags' => $DbIcjwL46hGJ2bDyfyF, 'errormsg' => $N4ipGZWhzqKWRPZ5, 'ntime' => $tQENWjLR97 ); unset($em308mW8OfU); Y1qFyrFH0Wg53("\n<-<-<- ".$jxBePD6_QbDAU."\n",3); if ($grab_parameters['xs_inc_ajax']  && strstr($NDMyPgjiu_2Ct0h3d, '"fragment"') && preg_match('#<meta[^>]*name\s*=\s*"fragment"[^>]*content\s*=\s*"!"#is', $NDMyPgjiu_2Ct0h3d) && !strstr($p8T45JUb9e3DW, 'escaped_fragment') && !strstr($p8T45JUb9e3DW, '#!') ) { $JCnAD3fPyhsy = $p8T45JUb9e3DW.'#!'; $rt = $this->fetch($JCnAD3fPyhsy, $dp + 1, $NEt1cUw2KEn, $VIxtBlYRjsX, $lSFBqQwj7ga3_AMU, $XHIdeP3juz3CM); } $rt['last_url'] = $p8T45JUb9e3DW; if (substr($CNu7KqULORVHvcnnw,0,2) == '30') { $JCnAD3fPyhsy = $this->oqRPvYYVrRueB23($YMptMARqVaIK['location']); $HZ8UgFn3R4ffMHTejWm = ''; if (substr($JCnAD3fPyhsy,0,2) == "//") {
																														 $JCnAD3fPyhsy = $kdDa6HNP9Z9['scheme'].":" . $JCnAD3fPyhsy; } if (!strstr($JCnAD3fPyhsy, "://")) {
																														 if ($JCnAD3fPyhsy[0] == "/") $HZ8UgFn3R4ffMHTejWm = $kdDa6HNP9Z9['scheme']."://" . $kdDa6HNP9Z9['host'];
																														 else $HZ8UgFn3R4ffMHTejWm = $kdDa6HNP9Z9['scheme']."://" . $kdDa6HNP9Z9['host'] . Xz3u7KwMuNzZ0p($kdDa6HNP9Z9['path']);
																														 } $JCnAD3fPyhsy = PpV5U2ubaMUby9SliLO($HZ8UgFn3R4ffMHTejWm, $JCnAD3fPyhsy); $JCnAD3fPyhsy = preg_replace('#\:\/\/' . preg_quote($kdDa6HNP9Z9['host'], '#') . '#i', '://' . $kdDa6HNP9Z9['host'], $JCnAD3fPyhsy);
																														 $cdttl4eioR  = $this->E2E9gSbIfq($JCnAD3fPyhsy); $EMFMeTX3WRjuOme = ($kdDa6HNP9Z9['host'] == $cdttl4eioR['host']); if(!$EMFMeTX3WRjuOme && $grab_parameters['xs_allow_subdomains']){ $QQ4p9CDWnkySpQVP = preg_replace('#^(www|\w)\.#', '', $kdDa6HNP9Z9['host']); $EMFMeTX3WRjuOme = $cdttl4eioR['host'] && preg_match('#^(.*?\.)?'.preg_quote($QQ4p9CDWnkySpQVP,'#').'$#', $cdttl4eioR['host']); } if ($EMFMeTX3WRjuOme && $NEt1cUw2KEn) { $rt = $this->fetch($JCnAD3fPyhsy, $dp + 1, $NEt1cUw2KEn, $VIxtBlYRjsX, $lSFBqQwj7ga3_AMU, $XHIdeP3juz3CM); }else { $rt['last_url'] = $JCnAD3fPyhsy; } } $this->Kr7ycupohBtDfNjB(".http-DONE\n"); return $rt; } function Ovk_XEMjSD($s) { return $this->ZMDplgTSqk($s); preg_match_all('#([^\r\n]*\r?\n)#s', $s, $dBRX2rAjZ8); $bii91JYowKmyH = ''; for ($i = 0; $i < count($dBRX2rAjZ8[1]); $i++) { $pozZMFC2EQYLeiYTDbW  = hexdec(trim($dBRX2rAjZ8[1][$i])); $xEwyOxvrXkrmjTi2dBG = ''; if (!$i && !$pozZMFC2EQYLeiYTDbW) return $s; if (!$pozZMFC2EQYLeiYTDbW) break; do { $xEwyOxvrXkrmjTi2dBG .= $dBRX2rAjZ8[1][++$i]; } while ((strlen($xEwyOxvrXkrmjTi2dBG) < $pozZMFC2EQYLeiYTDbW || !trim($dBRX2rAjZ8[1][$i + 1])) && ($i < count($dBRX2rAjZ8[1]))); $bii91JYowKmyH .= trim($xEwyOxvrXkrmjTi2dBG); } return $bii91JYowKmyH; } function ZMDplgTSqk($Sw1niIPgH3) { $fPFHSfAQq71RkmX4     = 0; $sKN_Ioxw7gu0PaqovV     = strlen($Sw1niIPgH3); $avPMw7uD5U = null; while (($fPFHSfAQq71RkmX4 < $sKN_Ioxw7gu0PaqovV) && ($U4Nnloj_HyCC = substr($Sw1niIPgH3, $fPFHSfAQq71RkmX4, ($XFpJFs17tggfYpp = strpos($Sw1niIPgH3, "\n", $fPFHSfAQq71RkmX4 + 1)) - $fPFHSfAQq71RkmX4))) { if (!$this->oRMWEJFSCl3($U4Nnloj_HyCC)) { return $Sw1niIPgH3; } $fPFHSfAQq71RkmX4      = $XFpJFs17tggfYpp + 1; $vIoYAtmgDPHsLBq = hexdec(rtrim($U4Nnloj_HyCC, "\r\n")); $avPMw7uD5U .= substr($Sw1niIPgH3, $fPFHSfAQq71RkmX4, $vIoYAtmgDPHsLBq); $fPFHSfAQq71RkmX4 = @strpos($Sw1niIPgH3, "\n", $fPFHSfAQq71RkmX4 + $vIoYAtmgDPHsLBq) + 1; if ($xz++ > 10000) break; } return $avPMw7uD5U; } function oRMWEJFSCl3($IzwIFU6iAy) { $IzwIFU6iAy = strtolower(trim(ltrim($IzwIFU6iAy, "0"))); if (empty($IzwIFU6iAy)) { $IzwIFU6iAy = 0; } ; $p8lWNCnTbd07jJo0 = hexdec($IzwIFU6iAy); return ($IzwIFU6iAy == dechex($p8lWNCnTbd07jJo0)); } } global $BMbehimV7yzhTAnB; $BMbehimV7yzhTAnB = new HTTPFetch(); $BMbehimV7yzhTAnB->LToZhQ6j3m4lISSBRN(); 



































































































